# Generated by Django 3.2 on 2024-04-07 18:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_title', models.CharField(max_length=100)),
                ('policy_text', ckeditor.fields.RichTextField()),
                ('still_valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'policy',
                'verbose_name_plural': 'Policies',
            },
        ),
    ]
