# Generated by Django 3.2 on 2024-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'method',
                'verbose_name_plural': 'Shipping methods',
            },
        ),
    ]
